dist: bionic
language: python
os: linux
python:
- '3.8'
cache:
- pip
- apt
addons:
  apt:
    packages:
    - pandoc
    - texlive-latex-base
    - texlive-latex-extra
    - tree
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - texlive-generic-recommended
    - texlive-generic-extra
    - texlive-xetex
    - lmodern
deploy:
  cleanup: false
  edge: true
  email: hut23@turing.ac.uk
  keep_history: true
  local_dir: _site
  on:
    branch: master
  provider: pages
  strategy: git
  token: "$GITHUB_TOKEN"
  verbose: true
install:
- pip install --upgrade setuptools wheel
- pip install -r requirements.txt
- pip install git+https://github.com/jamespjh/greeter.git
- pip install git+https://github.com/jakevdp/JSAnimation.git
- gem install liquid -v 4.0.3 # Version from https://pages.github.com/versions/
- gem install jekyll -v 3.9.0 # Version from https://pages.github.com/versions/
- gem install redcarpet
- wget http://ftpmirror.gnu.org/gnu/make/make-4.3.tar.gz # update make to v4.3 (ensures wildcards return files in order)
- tar xvf make-4.3.tar.gz
- cd make-4.3
- ./configure
- make
- sudo make install
- cd ..
- rm -rf make-4.3.tar.gz make-4.3
- PATH=/usr/local/bin:$PATH
- make --version
script:
- python -c "import matplotlib.pyplot"
- make
before_install:
- sudo add-apt-repository -y ppa:mc3man/bionic-media
- sudo apt-get -y update
- sudo apt-get -y install ffmpeg
