contact: https://www.turing.ac.uk/research/research-engineering

title: "Research Software Engineering with Python"
includeleftnav: True
short: RSEPython

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /rsd-engineeringcourse

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough","tables"]


include:
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_static"
  - "ch04packaging/greetings/doc/_modules"
exclude:
  - "*/*.nbconvert.ipynb"
  - "*/*.v2.ipynb"
  - "combined_files"
  - "combined.ipynb"
